language: python
python:
  - 2.7
env:
  - LOGGER_SETTINGS_FILE=./config.ini
install: 
  - python setup.py install
script:
  - python setup.py test
before_script:
  - cp ./config.ini.template ./config.ini
  - cp logger/robots.txt ./robots.txt
